<?= $this->doctype() ?>
<html>
<head>
    <?= $this->headMeta(); ?>
    <?= $this->headTitle(); ?>
    <?= $this->headStyle(); ?>
    <?= $this->headLink(); ?>
</head>
<body>
<div id="page_wrap">
    <?= $this->partial('partials/header.phtml') ?>
    <section id="content" class="container">
        <?= $this->layout()->content ?>
    </section>
    <div class="push"></div>
</div>
<?= $this->partial('partials/footer.phtml') ?>
<?= $this->headScript(); ?>
</body>
</html>

