<div class="jumbotron">
    <div class="row">
        <div class="col-md-8">
            <h1>Welcome to ZF Shop!</h1>

            <p>
                Etiam et libero aliquet sapien adipiscing tristique eu malesuada dui. Etiam erat nulla, eleifend non
                arcu a, pellentesque rutrum turpis. Nullam pellentesque facilisis adipiscing. Integer at est volutpat,
                luctus erat et, vestibulum nibh.
            </p>

            <ul>
                <li>Nunc commodo vestibulum quam ut vehicula.</li>
                <li>Ut volutpat congue augue, quis egestas lectus pulvinar et.</li>
                <li>Curabitur bibendum lorem enim, vel imperdiet velit suscipit eget.</li>
            </ul>
        </div>
        <div class="col-md-4">
            <img src="/i/product-image.png" alt="" class="img-responsive"/>
        </div>
    </div>
</div>

<h2>Popular products</h2>

<div class="row teasers">
    <?php foreach ($this->products as $product) : ?>
        <?= $this->partial('partials/product-teaser.phtml', array('product' => $product)) ?>
    <?php endforeach; ?>
</div>

<div class="row">
    <div class="col-md-8">
        <h2>About the shop</h2>

        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum adipiscing malesuada massa, eget
            imperdiet sem lobortis vitae. Aenean vestibulum sem non nisl ullamcorper, scelerisque dignissim justo
            gravida. Aliquam erat volutpat. Aenean lacinia, quam in faucibus luctus, nunc felis mollis nibh, non
            consequat enim quam vel sapien. Morbi pellentesque, turpis at placerat venenatis, nibh elit dapibus mi, in
            bibendum justo nisl eget justo. Donec vulputate dignissim purus, id pretium metus vulputate malesuada.
            Vivamus porttitor lectus nec velit sodales laoreet. Etiam lacinia odio nec mi egestas scelerisque.
        </p>

        <p>
            Integer imperdiet sodales iaculis. Cras lorem augue, imperdiet sed leo nec, euismod tincidunt augue. Sed
            dignissim enim a convallis facilisis. Quisque vitae lobortis eros. Maecenas feugiat diam libero, et auctor
            lorem vulputate a. Nam sagittis tincidunt risus, quis imperdiet tortor suscipit id. Nullam quis mi sit amet
            lorem pretium blandit. Aenean pretium egestas erat eget pretium.
        </p>
    </div>

    <aside class="col-md-4">
        <h2>Latest news</h2>

        <ul class="last-news">
            <li>
                <h3>Phasellus eu nibh sem.</h3>
                Praesent in sem massa. Pellentesque pulvinar viverra justo, vel semper orci suscipit ut.
            </li>
            <li>
                <h3>Phasellus eu nibh sem.</h3>
                Praesent in sem massa. Pellentesque pulvinar viverra justo, vel semper orci suscipit ut.
            </li>
        </ul>

    </aside>
</div>