<?php
$this->headTitle($this->product->name);
?>

<h1><?= $this->product->name ?></h1>

<div class="row product-page">
    <div class="col-md-4">
        <p>
            <img src="/i/product-image.jpg" alt="Picture of <?= $this->product->name ?>" class="img-responsive"/>
        </p>

        <div class="row">
            <div class="col-md-4">
                <img src="/i/product-image.jpg" alt="Picture of <?= $this->product->name ?>" class="img-responsive"/>
            </div>
            <div class="col-md-4">
                <img src="/i/product-image.jpg" alt="Picture of <?= $this->product->name ?>" class="img-responsive"/>
            </div>
            <div class="col-md-4">
                <img src="/i/product-image.jpg" alt="Picture of <?= $this->product->name ?>" class="img-responsive"/>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <p class="price">
            <?= $this->price($this->product->price) ?>
        </p>

        <p>
            <?= $this->product->description ?>
        </p>

        <p>
            <a href="<?= $this->url(array('controller' => 'cart', 'action' => 'add', 'sku' => $this->product->sku), 'default') ?>"
               class="btn btn-cart">
                Add to cart
                <i class="ic-cart"></i>
            </a>
        </p>
    </div>
</div>

<h2>Related products</h2>

<div class="row teasers">
    <?php foreach ($this->products as $product) : ?>
        <?= $this->partial('partials/product-teaser.phtml', array('product' => $product)) ?>
    <?php endforeach; ?>
</div>
