<?php
$this->headTitle($this->product->name);
?>

<h1><?= $this->product->name ?></h1>

<div class="row product-page">
    <div class="col-md-3">
        <img src="/i/product-image.jpg" alt="Picture of <?= $this->product->name ?>" class="img-responsive"/>
    </div>
    <div class="col-md-6">
        <p class="price">
            <?= $this->price($this->product->price) ?>
        </p>

        <p>
            Morbi dictum posuere magna id rutrum. Nulla facilisi. Vivamus varius quam justo, a rutrum libero elementum
            ultrices. Aenean et laoreet massa. Vivamus diam libero, scelerisque non commodo sed, dignissim at mauris.
            Vestibulum ac erat molestie arcu ultricies rutrum at quis neque. Phasellus eget hendrerit arcu.
        </p>

        <p>
            <a href="<?= $this->url(array('controller' => 'cart', 'action' => 'add', 'product' => $this->product->id), 'default') ?>"
               class="btn btn-cart">
                Add to cart
                <i class="ic-cart"></i>
            </a>
        </p>
    </div>
</div>

<h2>Related products</h2>

<div class="row teasers">
    <?php foreach ($this->products as $product) : ?>
        <div class="col-md-4">
            <a href="<?= $this->url(array('product' => $product->id), 'product') ?>"
               class="teaser">
                <h4><?= $product->name ?></h4>

                <p class="price"><?= $this->price($product->price) ?></p>
            </a>
        </div>
    <?php endforeach; ?>
</div>
