<footer>
    <div class="container">
        <div class="row">
            <div class="col-xs-6">
                ZF Shop &copy; 2014 <a href="mailto:andrew.ovcharov@gmail.com">Andrey Ovcharov</a>
            </div>
            <div class="col-xs-6 text-right">
                <a href="http://www.linkedin.com/in/snakeye"><i class="ic-linkedin"></i></a>
                <a href="https://www.xing.com/profile/Andrey_Ovcharov2"><i class="ic-xing"></i></a>
            </div>
        </div>
    </div>
</footer>
